### ISSUE TITLE
Looksee[] and ls method is not work in ActiveRecord instance.

### ISSUE THREAD

**Issue by zw963** [oggy/looksee#31] opened 2014-10-14 11:56 UTC
When in rails console, ls and Looksee[] seem like not work on ActiveRecord instance in some case.

```sh
pry):0> user.ls
SystemStackError: stack level too deep
from /home/zw963/.rvm/gems/ruby-2.1.1@neil-rails-app/gems/pry-0.10.0/lib/pry/pry_instance.rb:353
(pry):0> Looksee[user]
(pry) output error: #<NoMethodError: undefined method `is_a?' for #<#<Module:0x00000002e66430>:0x00000002e65c88>>
```

but, in this situation, I can use `user.methods` to return user all methods.

**Comment by oggy** [comment] 2015-01-06 06:10
I'm still unable to reproduce this. Maybe something has been
fixed in the awesome_print gem? Here's exactly what I tried:

* rails _4.1.0_ new looksee_test
* create & run a migration that adds an empty users table
* create empty user model

* add this to gemfile & bundle (installed awesome_print 1.2.0 and looksee 2.1.1):
gem 'awesome_print'
gem 'looksee'

* start rails console & run:
AwesomePrint.irb!
Looksee[User.new]

Some variations I tried:

* Doing User.create then User.first to instantiate the user.
* Starting irb like this instead of a rails console (to prevent my ~/.irbrc from loading):
  * irb -I. -f -rconfig/environment

So I'll need more detailed steps to be able to investigate.

**Comment by oggy** [comment] 2015-02-06 23:21
Closing due to staleness.

**Closed by oggy** 2015-02-06 23:21 UTC

**Comment by zw963** [comment] 2015-02-11 02:26
Sory for confuse, yesterday I spend many hours to find out what happen.
finally, I found seem like looksee gem binary compile error cause this. (I compile myself.)
I recompile it with look 3.1.0, is work ok. so, it is my fault.

Anyway, very thanks for you help,  thanks for you great fancy gem, I can not leave it everyday.
